### ISSUE TITLE
createruntimetexture native is call limited.

### ISSUE THREAD

**Issue by negbook** [sadboilogan/image-to-txn#1]
I don't suggest to create runtime textures directly at this moment.
I am using something to get data,and create that runtime textures remotely with runtime texture managers.
So that It can be usually reusing the old created runtime texture instead create new one. (bug after called 125~128times )
https://forum.cfx.re/t/request-something-to-destory-created-runtime-texture/4748766

**Comment by logan-mcgee** [comment]
Whole reason i have it as such is so that i could pass the width/height of the actual rendered image along from nui, as opposed to the user having to *manually* do that

**Comment by logan-mcgee** [comment]
got bored, decided to rewrite it in order to have the user pass the texture, should hopefully be fine now
